srt
udacity-china-translation/srt-translation-2017-07-drklug pull request #1
Opened 2017-08-20 09:12 UTC by drklug

翻译字幕任务 A39

2017-08-23 14:22 UTC, ivylee0919 requested changes
做的不错！👍有个别地方的语言组织还需要斟酌一下，因为看视频时，字幕一闪而过，语言表达需要简洁明了。
关于数字和英文的空格，如果数字后面的英文是单位，则不需要空格，比如 10cm，如果是中文单位，则需要空格，比如 10 厘米
再优化下语句表达，加油💪

2017-08-23 14:22 UTC, ivylee0919 commented on locales/zh-cn/UhvyD_60esQ.srt
> +写出了并且在自己的电脑上运行了完整的程序
在自己电脑上编写并运行了完整的程序

2017-08-23 14:22 UTC, ivylee0919 commented on locales/zh-cn/UhvyD_60esQ.srt
> +你已经学会了如何定义函数和怎样写有关分支的代码
你学习了如何定义函数 以及如何使用分支编写代码

2017-08-24 02:29 UTC, drklug commented
@ivylee0919  翻译任务已经按照要求更改了 还有其他地方需要更改吗？

2017-08-24 02:30 UTC, ivylee0919 approved these changes

2017-08-24 02:31 UTC, ivylee0919 commented
没有了，恭喜试译通过！👍

2017-08-24 02:31 UTC, merged